services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: sinpres
      POSTGRES_PASSWORD: sinpres
      POSTGRES_DB: sinpres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
