/**
 * SINAPI maintenances importer — populates previous_code in the catalogs from a JSON
 * generated by sinapi-extractor (output/maintenances.json).
 *
 * Source format (produced by sinapi-extractor/src/extract_maintenances.py):
 *   [
 *     { "old_code": 11616, "new_code": 11281, "type": "INPUT" },
 *     { "old_code": 95261, "new_code": 95262, "type": "COMPOSITION" }
 *   ]
 *
 * No XLSX parsing happens here — the extractor handles all source format quirks
 * (sheet detection, header normalization, free-text substitution pattern matching).
 *
 * For each entry, we UPDATE previous_code on the row identified by `new_code` in
 * either item_catalog or composition_catalog. Clients consuming the API can then
 * detect substitutions via the previousCode field in responses and migrate their
 * local records.
 *
 * Usage:
 *   bun run src/db/import/maintenances.ts <path-to-maintenances.json>
 */

import { db } from '../client'
import { itemCatalog, compositionCatalog } from '../schema/civil-construction'
import { eq, sql } from 'drizzle-orm'
import { readFileSync } from 'fs'
import { resolve } from 'path'

export type MaintenanceType = 'INPUT' | 'COMPOSITION'

export interface MaintenanceEntry {
  old_code: number
  new_code: number
  type: MaintenanceType
}

function isValidEntry(e: unknown): e is MaintenanceEntry {
  if (typeof e !== 'object' || e === null) return false
  const obj = e as Record<string, unknown>
  return (
    typeof obj.old_code === 'number' &&
    typeof obj.new_code === 'number' &&
    (obj.type === 'INPUT' || obj.type === 'COMPOSITION')
  )
}

export function loadMaintenances(filePath: string): MaintenanceEntry[] {
  const raw = readFileSync(filePath, 'utf-8')
  const parsed = JSON.parse(raw)
  if (!Array.isArray(parsed)) {
    throw new Error('Input JSON must be an array of maintenance entries.')
  }

  const valid: MaintenanceEntry[] = []
  let invalid = 0
  for (const e of parsed) {
    if (isValidEntry(e)) valid.push(e)
    else invalid++
  }

  if (invalid > 0) {
    console.warn(`  ${invalid} invalid entries skipped`)
  }
  return valid
}

export async function runMaintenancesImport(filePath: string) {
  const path = resolve(filePath)
  console.log(`Reading maintenances from: ${path}`)

  const entries = loadMaintenances(path)
  console.log(`  -> ${entries.length} valid entries`)

  let inputsApplied = 0
  let inputsNotFound = 0
  let compsApplied = 0
  let compsNotFound = 0

  for (const entry of entries) {
    if (entry.type === 'INPUT') {
      const result = await db
        .update(itemCatalog)
        .set({ previousCode: entry.old_code, updatedAt: sql`NOW()` })
        .where(eq(itemCatalog.code, entry.new_code))
        .returning({ id: itemCatalog.id })
      if (result.length === 0) {
        inputsNotFound++
        console.warn(`[maintenances] INPUT new_code=${entry.new_code} not found in item_catalog`)
      } else {
        inputsApplied++
      }
    } else {
      const result = await db
        .update(compositionCatalog)
        .set({ previousCode: entry.old_code, updatedAt: sql`NOW()` })
        .where(eq(compositionCatalog.code, entry.new_code))
        .returning({ id: compositionCatalog.id })
      if (result.length === 0) {
        compsNotFound++
        console.warn(
          `[maintenances] COMPOSITION new_code=${entry.new_code} not found in composition_catalog`
        )
      } else {
        compsApplied++
      }
    }
  }

  console.log('')
  console.log('=== Maintenances import complete ===')
  console.log(`  Inputs:       ${inputsApplied} applied, ${inputsNotFound} not found`)
  console.log(`  Compositions: ${compsApplied} applied, ${compsNotFound} not found`)
}

if (import.meta.main) {
  const path = process.argv[2]
  if (!path) {
    console.error('Usage: bun run src/db/import/maintenances.ts <path-to-maintenances.json>')
    console.error('Generate this file with: python3 src/extract_maintenances.py <xlsx>')
    process.exit(1)
  }

  runMaintenancesImport(path)
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('Maintenances import failed:', err)
      process.exit(1)
    })
}
